theme: jekyll-theme-minimal

title: "  "
logo: /perfil.jpeg
description: "Eiver Rodriguez"
affiliation: University of Puerto Rico 
location: Mayagüez
researchgate_url: "https://www.researchgate.net/profile/Eiver-Rodriguez-Perez?ev=hdr_xprf"
show_downloads: false

