theme: jekyll-theme-minimal

title: " "
logo: /perfil.jpeg

description: "Research interests:<br>Boolean functions<br>Exponential sums<br>Variable exponent spaces<br>Composition operators"

show_downloads: false

researchgate_url: "https://www.researchgate.net/profile/Eiver-Rodriguez-Perez?ev=hdr_xprf"
